config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :character_classes, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]
  resources :races, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]
  resources :archetypes, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]

  resources :characters do
    member do
      get :toggle_status
    end
  end
  
  get 'about', to: 'pages#about'
  get 'public-characters', to: 'pages#public_characters'
  get 'character/:id', to: 'characters#show', as: 'character_show'
  get 'admin-dashboard', to: 'pages#admin_dashboard'

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Character Share", sticky: false ) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Character Share", sticky: false ) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Character Share", sticky: false ) %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
      <div class="container">
        <span class="footer-text"><%= copyright_generator %>
</span>
      </div>
    </footer>

app/views/shared/_nav.html.erb
  <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top nav-header">
        <a class="navbar-brand" href="<%= root_path %>">Character Share</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'About', about_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Public Characters', public_characters_path, class: 'nav-link' %>
            </li>
            <% if current_user.is_a?(GuestUser) %>
            <li class="nav-item">
              <%= link_to "Register", new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
            </li>
            <% elsif current_user %>
            <li class="nav-item">
              <%= link_to 'My Characters', characters_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Edit User", edit_user_registration_path, class: 'nav-link' %>
            </li>
            <% end %>
            <% if logged_in?(:site_admin) %>
            <li class="nav-item">
              <%= link_to "Admin Dashboard", admin_dashboard_path, class: 'nav-link' %>
            </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>