config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :character_classes, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]
  resources :races, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]
  resources :archetypes, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]

  resources :characters do
    member do
      get :toggle_status
    end
  end
  
  get 'about', to: 'pages#about'
  get 'public-characters', to: 'pages#public_characters'
  get 'character/:id', to: 'characters#show', as: 'character_show'
  get 'admin-dashboard', to: 'pages#admin_dashboard'

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/admin_dashboard.html.erb
<div class="card">
<h1>Admin Dashboard</h1>
<br>
<h3>Characters</h3>
<div class="row">
  <div class="table-block">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Level</th>
      <th scope="col">Race</th>
      <th scope="col">Class</th>
      <th scope="col">Created By</th>
      <th scope="col">Date</th>
    </tr>
  </thead>

  <tbody>
<% @character.each do |character| %>
    <tr>
      <th scope="row"><%= link_to "#{character.name}", character_show_path(character) %></th>
      <td><%= character.level%></td>
      <td><%= character.race.race_name %></td>
      <td><%= character.character_class.title %></td>
      <td class="data-meta"><%= character.user.name %></td>
      <td class="data-meta"><%= character.created_at %></td>
    </tr>
<% end %>
  </tbody>
</table>
</div>
</div>
<p class="center-row"><%= link_to 'New Character', new_character_path, class: 'btn btn-md btn-primary' %></p>


<hr>
<h3>Classes</h3>
<div class="row">
  <div class="table-block table-sm">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Features</th>      
    </tr>
  </thead>
  <tbody>
<% @character_class.each do |c| %>
  <tr>
      <th scope="row"><%= link_to c.title, character_class_path(c) %></th>
      <td><%= c.features.count %></td>
    </tr>
<% end %>
</tbody>
</table>

</div>
</div>
<p class="center-row"><%= link_to 'New Class', new_character_class_path, class: 'btn btn-md btn-primary' %></p>

<hr>
<h3>Races</h3>
<div class="row">
    <div class="table-block table-sm">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Traits</th>      
    </tr>
  </thead>
  <tbody>
<% @race.each do |r| %>
  <tr>
      <th scope="row"><%= link_to r.race_name, race_path(r) %></th>
      <td><%= r.traits.count %></td>
    </tr>
<% end %>
  </tbody>
</table>
</div>
</div>

<p class="center-row"><%= link_to 'New Race', new_race_path, class: 'btn btn-md btn-primary' %></p>

<div class="row">
  <%= @archetype.all %>
  <br>
  <p><%= link_to 'New Archetype', new_archetype_path, class: 'btn btn-md btn-primary' %></p>
</div>

</div>

app/views/pages/home.html.erb
<div class="inner cover main-page">
  <h1 class="cover-heading">Welcome <%= current_user.first_name %></h1>
  <p class="lead">You can store your character data here! Just sign up!</p>
</div>

app/views/pages/public_characters.html.erb
<div class="album">
  <div class="container">
<h1>Public Characters</h1>
<br>
    <div class="row">
    <% @character.each do |character| %>
      <div class="col-md-4">
        <div class="card">
          <%= image_tag character.character_image, width: '350px', class: 'card-img' %>
          <p class="card-text">
            <span><%= link_to character.name, character_show_path(character) %></span> <%= character.race.race_name %> <%= character.character_class.title %> <%= character.level %>
            <div class="data-meta">Created by: <%= character.user.name %></div>
          </p>
        </div>
      </div>
<% end %>

      
    </div>
  </div>
</div>