config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :character_classes, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]
  resources :races, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]
  resources :archetypes, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]

  resources :characters do
    member do
      get :toggle_status
    end
  end
  
  get 'about', to: 'pages#about'
  get 'public-characters', to: 'pages#public_characters'
  get 'character/:id', to: 'characters#show', as: 'character_show'
  get 'admin-dashboard', to: 'pages#admin_dashboard'

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/character.rb
class Character < ApplicationRecord
  enum status: {personal: 0, published: 1}
  extend FriendlyId
  friendly_id :name, use: :slugged
  mount_uploader :character_image, CharacterUploader

  validates_presence_of :name, :race_id, :character_class_id, :armor_class, :speed, :initiative, :level
  validates :level, :inclusion => 1..20
  belongs_to :character_class
  belongs_to :race
  belongs_to :user, optional: true
  has_many :stats, dependent: :destroy
  accepts_nested_attributes_for :stats,
                                allow_destroy: true,
                                reject_if: lambda {|attrs| attrs['name'].blank?}

  scope :characters_by, ->(user) { where(user_id: user.id) }

  def self.recent
    order("created_at DESC")
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:edit, :update, :destroy, :show, :toggle_status]
  def index
    if current_user.is_a?(GuestUser)
      redirect_to root_path, notice: "You need to be logged in to access this page"
    elsif current_user
      @character = Character.recent.characters_by(current_user)
    end
  end

  def new
  @character = Character.new
  6.times { @character.stats.build }
  
  end

  def create
    @character = Character.new(character_params)
    @character.user_id = current_user.id

    respond_to do |format|
      if @character.save
        format.html { redirect_to characters_path, notice: 'Character has been saved.' }
        
      else
        format.html { render :new }
      end 
    end
  end

  def edit
    
    
  end

  def update
    

    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to characters_path, notice: 'Character was successfully updated.' }
        
      else
        format.html { render :edit }
        
      end
    end
  end

  def show
    @character = Character.recent.friendly.find(params[:id])
  end

  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: "#{@character.name} has been deleted." }
      
    end
  end

  def toggle_status
    if @character.personal?
      @character.published!
    elsif @character.published?
      @character.personal!
    end
        
    redirect_to characters_url, notice: 'Character status has been updated.'
  end


  private

  def set_character
    @character = Character.friendly.find(params[:id])
    @character.user_id = current_user.id
  end

  def character_params
    params.require(:character).permit(:name,
                                      :race_id,
                                      :character_class_id,
                                      :level,
                                      :backstory,
                                      :status,
                                      :user_id,
                                      :equipment,
                                      :inventory,
                                      :armor_class,
                                      :initiative,
                                      :proficiency,
                                      :speed,
                                      :notes,
                                      :personality,
                                      :ideals,
                                      :bonds,
                                      :flaws,
                                      :age,
                                      :height,
                                      :weight,
                                      :eyes,
                                      :skin,
                                      :hair,
                                      :allies,
                                      :character_image,
                                      stats_attributes: [:name, :score, :modifier, :id, :_destroy]
                                      )
  end



end

app/helpers/characters_helper.rb
module CharactersHelper
  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def character_img img 
    if img.model.character_image?
      img
    else
      image_generator(height: '350', width: '350')
    end
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
  


end

app/views/characters/_form.html.erb
<%= form_for(@character) do |c| %>
  <% if character.errors.any? %>
    <% character.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Character Share", sticky: false ) %>
      <% end %>
    <% end %>


    <div class="row">
      <div class="col-md-5">
        
        <div class="form-group">
          <%= c.label :name %>
          <%= c.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= c.label :race %>
          <%= c.collection_select(:race_id, Race.all, :id, :race_name,
                                  {
                                    include_blank: false,

                                  },
                                  class: 'form-control'
                                  ) %> 
        </div>

        <div class="form-group">
          <%= c.label 'Class' %>
          <%= c.collection_select(:character_class_id, CharacterClass.all, :id, :title,
                                  {
                                    include_blank: false,

                                  },
                                  class: 'form-control'
                                  ) %>   

        </div>

        <div class="form-group">
          <%= c.radio_button :status, 'personal' %>
          <%= c.label :status, 'Personal' %>
          <%= c.radio_button :status, 'published' %>
          <%= c.label :status, 'Published' %>
        </div>

        
      </div>

      <div class="col-md-2">
        <div class="form-label-group">
          <%= c.label :level %>
          <%= c.number_field :level, class: 'form-control small-box' %>
        </div>

        <div class="form-label-group">
           <a tabindex="0" class="pop-link" data-placement="right" role="label" data-toggle="popover"  title="Proficiency" data-content="<%= "Levels 1-4 = +2, 
           Levels 5-8 = +3, Levels 9-12 = +4, Levels 13-16 = +5, Levels 17-20 = +6" %>">
          <%= c.label :proficiency %></a>
          <%= c.number_field :proficiency, class: 'form-control small-box' %>
        </div>

        <div class="form-label-group">
          <%= c.label :armor_class %>
          <%= c.number_field :armor_class, class: 'form-control small-box' %>
        </div>
        <div class="form-label-group">
          <%= c.label :initiative %>
          <%= c.text_field :initiative, class: 'form-control small-box' %>
        </div>
        <div class="form-label-group">
          <%= c.label :speed %>
          <%= c.number_field :speed, class: 'form-control small-box' %>
        </div>
      </div>

      <div class="col-md-5">
        <div class="form-group">
          <label class="btn btn-primary">
            Upload a character image <%= c.file_field :character_image, style: 'display:none;' %>     
          </label>
        </div>

        <div class="form-group">
          <%= image_tag @character.character_image, width: '200px' %>
        </div>
    </div>
  </div>

  <div class="row">

    <p><h3>Stats</h3></p>
    </div>
    <div class="row stat">

      <%= c.fields_for :stats do |s| %>
        <div class="card stat-item">
          <div class="form-group">
            <%= s.label :name %>
            <%= s.text_field :name, class: 'form-control' %>
              
          </div>

          <div class="form-group">
            <%= s.label :score %>
            <%= s.number_field :score, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= s.label :modifier %>
            <%= s.text_field :modifier, class: 'form-control' %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= c.label :equipment %>
          <%= c.text_area :equipment, class: 'form-control', rows: 8 %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= c.label :inventory %>
          <%= c.text_area :inventory, class: 'form-control', rows: 8 %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
  <div class="form-group">
    <%= c.label :backstory %>
    <%= c.text_area :backstory, class: 'form-control', rows: 5 %>
  </div> 
</div>
  <div class="col-md-6">
  <div class="form-group">
    <%= c.label :notes %>
    <%= c.text_area :notes, class: 'form-control', rows: 5 %>
  </div>
</div>
</div>

  <div class="row">
    <div class='col-md-6'>
  <div class="form-group">
    <%= c.label :age %> 
    <%= c.number_field :age, class: 'form-control' %>
  </div> 
  <div class="form-group">
    <%= c.label :height %>
    <%= c.text_field :height, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= c.label :weight %>
    <%= c.text_field :weight, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= c.label :eyes %>
    <%= c.text_field :eyes, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= c.label :skin %>
    <%= c.text_field :skin, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= c.label :hair %>
    <%= c.text_field :hair, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= c.label :allies %>
    <%= c.text_area :allies, class: 'form-control', rows: 6 %>
  </div>
</div>


    <div class='col-md-6'>
  <div class="form-group">
    <%= c.label :personality %>
    <%= c.text_area :personality, class: 'form-control', rows: 5 %>
  </div>
  <div class="form-group">
    <%= c.label :ideals %>
    <%= c.text_area :ideals, class: 'form-control', rows: 5 %>
  </div>
  <div class="form-group">
    <%= c.label :bonds %>
    <%= c.text_area :bonds, class: 'form-control', rows: 5 %>
  </div>
  <div class="form-group">
    <%= c.label :flaws %>
    <%= c.text_area :flaws, class: 'form-control', rows: 5 %>
  </div>
</div>
</div>

  

  <hr>

  <div class="form-group">
    <%= c.submit 'Save Character', class: 'btn btn-primary btn-block' %>
  </div>

<% end %>

<div><%= link_to 'Back', characters_path, class: 'btn btn-warning btn-block' %></div>

app/views/characters/edit.html.erb
<div class="container character-container">
  <div class="card">
  <h3>Edit Character</h3>

  <div><%= render 'form', character: @character %></div>
</div>
</div>

app/views/characters/index.html.erb
<div class="album">
  <div class="container">
<h1>My Characters</h1>
<br>
    <div class="row bob">
    <% @character.each do |character| %>
      <div class="col-md-4">
        <div class="card">
          <%= image_tag character.character_image, width: '350px', class: 'card-img' %>
          <p class="card-text">
            <div><h5><span><%= link_to character.name, character_show_path(character) %></span></h5></div> 
            <%= character.race.race_name %>, <%= character.character_class.title %> Level: <%= character.level %>
            <div class="data-meta">Created at: <%= character.created_at %> by: <%= character.user.name %></div>
          </p>
        </div>
      </div>
<% end %>

    </div>
    <hr>
    <div class="row center-row">
<div class="button-item"><%= link_to 'New Character', new_character_path, class: 'btn btn-primary btn-lg' %></div>
  </div>
</div>
</div>

app/views/characters/new.html.erb
<div class="container character-container">
  <div class="card">
<h3>Create New Character</h3>
<div><%= render 'form', character: @character %></div>
</div>
</div>

app/views/characters/show.html.erb
<div class="container show-container">
  <div class="card">

<% if @character.personal? %>
  <h3>This character is Private</h3>
<% elsif @character.published? %>
  <h3>This character is Public</h3>
<% end %>
<h2><%= @character.name %></h2>
<div class="row">
  <div class="col-md-3">
<h5><a tabindex="0" container="body" class="pop-link" data-placement="right" role="label" data-toggle="popover" data-trigger="focus" title="<%= @character.race.race_name %>" data-content="<%= @character.race.race_description %>"><%= @character.race.race_name %></a></h5>
<h5><a tabindex="0" container="body" class="pop-link" data-placement="right" role="lable" data-toggle="popover" data-trigger="focus" title="<%= @character.character_class.title %>" data-content="<%= @character.character_class.description %>"><%= @character.character_class.title %>, Level <%= @character.level %></a></h5>

<div class="row">
<div class="stat-box card col"><div><b>AC</b></div><div><%= @character.armor_class %></div></div>
<div class="stat-box card col"><div><b>Initiative</b></div><div><%= @character.initiative %></div></div>
</div>
<div class="row">
<div class="stat-box card col"><div><b>Speed</b></div><div><%= @character.speed %></div></div>

<div class="stat-box card col"><div><b>Bonus</b></div><div>+<%= @character.proficiency %></div></div>
</div>

</div>
<div class="col-md-5">
<% @character.stats.recent.each do |stat| %>
<div class="stat-block card stat-box col">
    <div><b><%= stat.name %></b></div> <div><%= stat.score %></div> <div><%= stat.modifier %></div>
  </div>
<% end %>
</div>

<div class="col-md-4 char-img">
  <div><%= image_tag character_img(@character.character_image), width: '100%', style: 'margin-right:20px;border-radius:4px;', alt: 'character image' %></div>
</div>
</div>


    <div class="row trait-row">
      <div class="class-item">
  <h3>Class Features</h3>
  <ul>
  <% @character.character_class.features.each do |feature| %>
    <% if  @character.level >= feature.level %>
      <li>
        <%= feature.name %> Level: <%= feature.level %>, <%= feature.description %> 
      </li>
      <br>
    <% end %>
  <% end %>
</ul>
</div>
<div class="class-item">
  <h3>Racial Traits</h3>
  <ul>
  <% @character.race.traits.each do |trait| %>
      <li>
        <%= trait.name %>: <%= trait.description %> 
      </li>
      <br>
  <% end %>
</ul>
</div>
</div>

<div class="row">
  <div class="col-sm text-field">
    <h4>Inventory</h4>
    <%= markdown @character.inventory %>
  </div>

  <div class="col-sm text-field">
    <h4>Equipment</h4>
    <%= markdown @character.equipment %>
  </div>

  <div class="col-sm text-field">
    <h4>Notes</h4>
    <%= markdown @character.notes %>
  </div>
  
</div>

<hr>

<h3>Secondary Details</h3>
<br>

<div class="row align-items-center">
  <div class="col-sm text-field-sm">
    <h5>Personality</h5>
    <%= markdown @character.personality %>
  </div>
  <div class="col-sm text-field-sm">
    <h5>Ideals</h5>
    <%= markdown @character.ideals %>
  </div>
  <div class="col-sm text-field-sm">
    <h5>Bonds</h5>
    <%= markdown @character.bonds %>
  </div>
  <div class="col-sm text-field-sm">
    <h5>Flaws</h5>
    <%= markdown @character.flaws %>
  </div>

</div>

<div class="row justify-content-md-center">

  <div class="col-md-auto">

    <div class"col-sm-auto>

      <div class="stat-box card">
        Age: <%= @character.age %>
      </div>
      <div class="stat-box card">
        Height: <%= @character.height %>
      </div>
      <div class="stat-box card">
        Weight: <%= @character.weight %> lbs
      </div>
    </div>

    <div class"col-sm-auto>
      <div class="stat-box card">
        Skin: <%= @character.skin %>
      </div>
      <div class="stat-box card">
        Eyes: <%= @character.eyes %>
      </div>
      <div class="stat-box card">
        Hair: <%= @character.hair %>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="row">
    <div class="text-field-sm">
      <h5>Backstory</h5>
      <%= @character.backstory %>
    </div>
  </div>
    <div class="row">
    <div class="text-field-sm">
      <h5>Allies, Factions, and Organizations</h5>
      <%= markdown @character.allies %>
    </div>
  </div>
  </div>
</div>
<hr>
  

<div class="row center-row">
  <% if logged_in?(:site_admin) %>
    <div class="button-item"><%= link_to "Edit Character", edit_character_path(@character), class: 'btn btn-primary btn-lg' %></div>
    <div class="button-item"><%= link_to 'Delete Character', @character, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary btn-lg' %></div>
  <% elsif current_user.id == @character.user_id %>
    <div class="button-item"><%= link_to "Edit Character", edit_character_path(@character), class: 'btn btn-primary btn-lg' %></div>
    <div class="button-item"><%= link_to 'Delete Character', @character, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary btn-lg' %></div>
  <% end %>
  <div class="button-item"><%= link_to 'Back', characters_path, class: 'btn btn-warning btn-lg' %></div>
</div>



</div>
</div>