config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :character_classes, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]
  resources :races, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]
  resources :archetypes, only: [:index, :show, :destroy, :new, :create, :update, :edit, :sort]

  resources :characters do
    member do
      get :toggle_status
    end
  end
  
  get 'about', to: 'pages#about'
  get 'public-characters', to: 'pages#public_characters'
  get 'character/:id', to: 'characters#show', as: 'character_show'
  get 'admin-dashboard', to: 'pages#admin_dashboard'

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/character_classes_controller.rb
class CharacterClassesController < ApplicationController
  before_action :set_character_class, only: [:edit, :update, :destroy, :show]
  access site_admin: :all

  def index
    @character_classes = CharacterClass.all
  end

  def show
    
  end

  def new
  @character_class = CharacterClass.new
  
  end

  def create
    @character_class = CharacterClass.new(character_class_params)

    respond_to do |format|
      if @character_class.save
        format.html { redirect_to admin_dashboard_path, notice: 'Class has been saved.' }
        
      else
        format.html { render :new }
      end 
    end
  end

  def edit
    
    
  end

  def update
    

    respond_to do |format|
      if @character_class.update(character_class_params)
        format.html { redirect_to admin_dashboard_path, notice: 'Class was successfully updated.' }
        
      else
        format.html { render :edit }
        
      end
    end
  end

  
  def destroy
    @character_class.destroy
    respond_to do |format|
      format.html { redirect_to admin_dashboard_path, notice: "#{@character_class.title} has been deleted." }
      
    end
  end

  private

  def set_character_class
    @character_class = CharacterClass.friendly.find(params[:id])
  end

  def character_class_params
    params.require(:character_class).permit(:title,
                                            :description,
                                            features_attributes: [:name, :description, :level, :id, :_destroy],
                                            archetypes_attributes: [:name, :level, :description, :id, :_destroy]                                      
                                            )
  end
end

app/views/character_classes/_feature_fields.html.erb
<div class="form-group">

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', rows: 5 %>
      </div>

      <div class="form-group">
        <%= f.label :level %>
        <%= f.number_field :level, class: 'form-control' %>
      </div>
      <div class="form-group">
     <%= link_to_remove_association 'Remove Feature', f, class: 'btn btn-md btn-danger' %>
   </div>

</div>

app/views/character_classes/_form.html.erb
<%= form_for(@character_class) do |c| %>
 <% if @character_class.errors.any? %>
    <% @character_class.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Character Share", sticky: false ) %>
      <% end %>
    <% end %>

  <div class="form-group">
    <%= c.label :title %>
    <%= c.text_field :title, class: 'form-control', width: '50%' %>
  </div>

  <div class="form-group">
    <%= c.label :description %>
    <%= c.text_area :description, class: 'form-control', rows: 5, width: '50%' %>
  </div>

  <div class="form-group">
  <h3>Features</h3> 
    <%= c.fields_for :features do |f| %>
      <%= render 'feature_fields', f: f %>
    <% end %>

     <div>
        <%= link_to_add_association 'Add Feature', c, :features, class: 'btn btn-md btn-secondary' %>
      </div>
    </div>

  <div class="form-group">
    <%= c.submit 'Save Class', class: 'btn btn-primary btn-block' %>
  </div>

<% end %>

<div><%= link_to 'Back', admin_dashboard_path, class: 'btn btn-warning btn-block' %></div>

app/views/character_classes/edit.html.erb
<div class="container character-container">
  <div class="card">
<h3>Edit class</h3>

<div><%= render 'form', character_class: @character_class %></div>
</div>
</div>

app/views/character_classes/new.html.erb
<div class="container character-container">
  <div class="card">
<h3>New Class</h3>

<div><%= render 'form', character_class: @character_class %></div>
</div>
</div>

app/views/character_classes/show.html.erb
<div>Class: <%= @character_class.title %></div>
<div>Description: <%= @character_class.description %></div>
<h3>Features:</h3>
<ul>
<% @character_class.features.each do |f| %>
  <li>
    <%= f.name %>, <%= f.description %>, <%= f.level %>
  </li>
<% end %>
  </ul>

<div>
  <% if logged_in?(:site_admin) %>
    <div><%= link_to "Edit Class", edit_character_class_path(@character_class) %></div>
    <div><%= link_to 'Delete Class', @character_class, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    <% end %>
  <div><%= link_to 'Back', admin_dashboard_path %></div>
</div>